### ISSUE TITLE
wrong boa-scan amount

### ISSUE THREAD

**Issue by RoscoPColtrane1** [bosagora/boa-scan#188]
hi,
The boa-scan website sometimes shows outdated information.

If i pull information from the website is shows different values.
For example refresh this page a couple of times:
https://boascan.io/api/v2/addresses/0x79f8095b1eDa1C89DCcfbB276adf7eBCb387F053

You will see that the amount of BOA jumps lower sometimes.
Can you make it stable again?
Thx.

**Comment by MichaelKim20** [comment]
@RoscoPColtrane1 Thank you for letting me know.
I immediately found the cause and then solved it.
We're running two servers. I've noticed that one of them has an abnormal symptom in the indexing part of the block. So I switched to another server.

**Comment by RoscoPColtrane1** [comment]
great work, you fixed it. :)
